# Generated by Django 4.1 on 2023-03-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accident', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccidentnData',
            new_name='AccidentData',
        ),
    ]
