beijing_route_hparams = {
    "hidden_dims": 608,
    "node_dims": 512,
    "node_num": 16000,
    "cmt_num": 200,
    "cmt_dims": 256,
    "struct_cmt_num": 300,
    "struct_cmt_dims": 608,
    "fnc_cmt_num": 30,
    "fnc_cmt_dims": 256,

    "train_cmt_set": "/home/mjt/HRNR/beijing/data/train_cmt_set",
    "train_loc_set": "/home/mjt/HRNR/beijing/data/train_loc_10_set",
    "train_time_set": "/home/mjt/HRNR/beijing/data/train_time_set_eta",
    "route_train_set": "/home/mjt/HRNR/beijing/data/route_train_set",
    "route_test_set": "/home/mjt/HRNR/beijing/data/route_test_set",
    "route_predict_set": "/home/mjt/test/HRNR/beijing/data/route_predict_set",
    "adj": "/home/mjt/HRNR/beijing/data/CompleteAllGraph",
    "t_adj": "/home/mjt/HRNR/beijing/data/loc_tra_adj",
    "type_adj": "/home/mjt/HRNR/beijing/data/type_adj",
    "poi_adj": "/home/mjt/HRNR/beijing/data/poi_adj_0.99",
    "node_features": "/home/mjt/HRNR/beijing/data/node_features",
    "spectral_label": "/home/mjt/HRNR/beijing/data/spectral_label",
    "struct_assign": "/home/mjt/HRNR/beijing/data/spectral_label",
    "fnc_assign": "/home/mjt/HRNR/beijing/data/fnc_assign",

    "gru_dims": 512,
    "gru_layers": 1,
    "is_bigru": True,
    "state_num": 2,
    "vocab_size": 16000,
    "batch_size": 100,
    "device": 0,
    "use_cn_gnn": False,
    "gnn_layers": 1,
    "eta_epoch": 20,
    "gae_epoch": 1,
    "eta_learning_rate": 1e-4,
    "gae_learning_rate": 5e-4,
    "g2s_learning_rate": 1e-4,
    "g2t_learning_rate": 1e-4,
    "lp_learning_rate": 1e-4,
    "loc_pred_gnn_layer": 1,

    "alpha": 0.2,
    "dropout": 0.6,

    "lane_num": 6,
    "length_num": 220,
    "type_num": 20,
    "lane_dims": 32,
    "length_dims": 32,
    "type_dims": 32,

    "clip": 0.1,
    "g2s_clip": 1.0,
    "g2t_clip": 1.0,
    "lp_clip": 1.0,

    "g2t_sample_num": 2000,
    "g2t_epoch": 1000,

    "baseline_gat_layer": 1,
}


beijing_hparams = {
    "hidden_dims": 608,
    "node_dims": 512,
    "node_num": 16000,
    "cmt_num": 200,
    "cmt_dims": 256,
    "struct_cmt_num": 300,
    "struct_cmt_dims": 608,
    "fnc_cmt_num": 30,
    "fnc_cmt_dims": 256,

    "train_cmt_set": "/home/mjt/HRNR/beijing/data/train_cmt_set",
    "train_loc_set": "/home/mjt/HRNR/beijing/data/train_loc_10_set",
    "train_time_set": "/home/mjt/HRNR/beijing/data/train_time_set_eta",
    "loc_train_set": "/home/mjt/HRNR/beijing/data/loc_train_set",
    "loc_test_set": "/home/mjt/HRNR/beijing/data/loc_test_set",
    "loc_predict_set": "/home/mjt/test/HRNR/beijing/data/loc_predict_set",
    "adj": "/home/mjt/HRNR/beijing/data/CompleteAllGraph",
    "t_adj": "/home/mjt/HRNR/beijing/data/loc_tra_adj",
    "type_adj": "/home/mjt/HRNR/beijing/data/type_adj",
    "poi_adj": "/home/mjt/HRNR/beijing/data/poi_adj_0.99",
    "node_features": "/home/mjt/HRNR/beijing/data/node_features",
    "spectral_label": "/home/mjt/HRNR/beijing/data/spectral_label",
    "struct_assign": "/home/mjt/HRNR/beijing/data/struct_assign_with_type",
    "fnc_assign": "/home/mjt/HRNR/beijing/data/fnc_assign_without_poi",

    "gru_dims": 512,
    "gru_layers": 1,
    "is_bigru": True,
    "state_num": 2,
    "vocab_size": 16000,
    "batch_size": 300,
    "device": 1,
    "use_cn_gnn": False,
    "gnn_layers": 1,
    "eta_epoch": 20,
    "gae_epoch": 1,
    "eta_learning_rate": 1e-4,
    "gae_learning_rate": 5e-4,
    "g2s_learning_rate": 1e-4,
    "g2t_learning_rate": 1e-4,
    "lp_learning_rate": 1e-4,
    "loc_pred_gnn_layer": 1,

    "alpha": 0.2,
    "dropout": 0.6,

    "lane_num": 6,
    "length_num": 220,
    "type_num": 20,
    "lane_dims": 32,
    "length_dims": 32,
    "type_dims": 32,

    "clip": 0.1,
    "g2s_clip": 1.0,
    "g2t_clip": 1.0,
    "lp_clip": 1.0,

    "g2t_sample_num": 2000,
    "g2t_epoch": 1000,

    "baseline_gat_layer": 1,
}
