# Generated by Django 3.2.15 on 2023-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_nextlocdata_nextlochyperparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedPredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='traffic')),
                ('type', models.CharField(default='speed_prediction_data', max_length=50, verbose_name='Data Type')),
            ],
        ),
        migrations.CreateModel(
            name='SpeedPredictionHyperparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epochs', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('lr', models.FloatField()),
                ('dropout', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='accidentdata',
            name='type',
            field=models.CharField(default='accident_data', max_length=50, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='nextlocdata',
            name='type',
            field=models.CharField(default='next_loc_data', max_length=50, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='routeplandata',
            name='type',
            field=models.CharField(default='route_plan_data', max_length=50, verbose_name='Data Type'),
        ),
    ]
