# Generated by Django 3.2.5 on 2022-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poptraffic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='POI/')),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='trajectory/')),
            ],
        ),
        migrations.AlterField(
            model_name='roadnetworkdata',
            name='file',
            field=models.FileField(null=True, upload_to='road_network/'),
        ),
    ]
