# Generated by Django 4.0.4 on 2022-05-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poptraffic', '0002_auto_20220513_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopTrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='pop_traffic')),
                ('type', models.CharField(max_length=50, verbose_name='Data Type')),
            ],
        ),
        migrations.DeleteModel(
            name='POIData',
        ),
        migrations.DeleteModel(
            name='RoadNetworkData',
        ),
        migrations.DeleteModel(
            name='TrajectoryData',
        ),
    ]
